APPLY_FIXES: all
CLEAR_REPORT_FOLDER: true
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - REPOSITORY_KICS
EXCLUDED_DIRECTORIES:
  - .devcontainer
  - .vscode
  - .zed
FILEIO_REPORTER: false
IGNORE_GITIGNORED_FILES: true
MARKDOWN_MARKDOWN_LINK_CHECK_CONFIG_FILE: markdown-link-check.json
SHOW_ELAPSED_TIME: true
SPELL_CSPELL_ANALYZE_FILE_NAMES: false
